import './globals.css'
import type { Metadata } from 'next';
import classnames from 'classnames';
import { assets } from '@/shared/config/images';
import Image from 'next/image';
import { Header } from '@/widgets/header';


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="ru">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link
          href="https://fonts.googleapis.com/css2?family=Ubuntu:wght@300;400;500;700&family=Unbounded:wght@200;300;400;500;600;700;800;900&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className="backdrop-blur-[100px] bg-[#fff] h-full">
        {/* <Header /> */}
        {children}
      </body>
    </html>
  )
}
